### ISSUE TITLE
Logout problem

### ISSUE THREAD

**Issue by wintercomic** [onelogin/joomla-saml#1]
Hello,

Currently I am implementing  SSO between ADFS and Joomla. I install the plugin and get logout work.

When I click the logout in Joomla, I get the the following error message in ADFS:

```
Encountered error during federation passive request. 

Additional Data 

Protocol Name: 


Relying Party: 


Exception details: 
System.Xml.XmlException: ID4263: The SAML NameIdentifier 'http://xxxxxxxxx/adfs/services/trust' is of format 'urn:oasis:names:tc:SAML:2.0:nameid-format:entity' and NameQualifier/SPNameQualifier/SPProvidedID is not omitted.
```

ADFS receive the following message:

```
<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                     ID="ONELOGIN_34222a6b1c7896f6433b74e713848c206af5c26a"
                     Version="2.0"
                     IssueInstant="2016-08-26T08:13:02Z"
                     Destination="https://ADFS/adfs/ls/"
                     >
    <saml:Issuer>http://joomla/sp</saml:Issuer>
    <saml:NameID SPNameQualifier="http://joomla/sp"
                 Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                 >ADFS</saml:NameID>
</samlp:LogoutRequest>
```

Joomla pass the wrong NameID format to ADFS. I am using urn:oasis:names:tc:SAML:2.0:nameid-format:transient in settings.
I look at the oneloginsaml.php in plg_user_oneloginsaml, and find logout call the following functions:

```
else if (isset($_GET['slo'])) {
        $saml_auth->logout();
    }
```

I think because it doesn't pass the Name ID when call logout(). When process logout, it will use urn:oasis:names:tc:SAML:2.0:nameid-format:entity for creating logout request.

In /Joomla-base/libraries/onelogin/lib/Saml2/LogoutRequest.php, line 66:

```
            if (!empty($nameId)) {
                $nameIdFormat = $spData['NameIDFormat'];
                $spNameQualifier = null;
            } else {
                **$nameId = $idpData['entityId'];
                $nameIdFormat = OneLogin_Saml2_Constants::NAMEID_ENTITY;
                $spNameQualifier = $spData['entityId'];**
            }

            $nameIdObj = OneLogin_Saml2_Utils::generateNameId(
                $nameId,
                $spNameQualifier,
                $nameIdFormat,
                $cert
            );

            $sessionIndexStr = isset($sessionIndex) ? "<samlp:SessionIndex>{$sessionIndex}</samlp:SessionIndex>" : "";

            $logoutRequest = <<<LOGOUTREQUEST
<samlp:LogoutRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="{$id}"
    Version="2.0"
    IssueInstant="{$issueInstant}"
    Destination="{$idpData['singleLogoutService']['url']}">
    <saml:Issuer>{$spData['entityId']}</saml:Issuer>
    {$nameIdObj}
    {$sessionIndexStr}
</samlp:LogoutRequest>
LOGOUTREQUEST;
        }
```

Does Joomla save the NameId format and sessionIndex when login? Can I pass these two parameter when call logout method?

Thank you very much.

**Comment by pitbulk** [comment]
You are right.

I should save the NameID and the SessionIndex at [oneloginsaml.php](https://github.com/onelogin/joomla-saml/blob/master/plg_user_oneloginsaml/oneloginsaml.php#L210) as [I do on the demo1 example](https://github.com/onelogin/php-saml/blob/master/demo1/index.php#L72)

```
            // SSO SAML Login flag
            $session->set('saml_login', 1);

            $nameId = $auth->getNameId();
            $session->set('saml_nameid', $nameId);

            $sessionIndex = $auth->getSessionIndex();
            $session->set('saml_sessionindex', $sessionIndex);
```

So later on the [logout call](https://github.com/onelogin/joomla-saml/blob/master/plg_user_oneloginsaml/oneloginsaml.php#L266) I will be able to call it with parameters, as [I do on the demo1](https://github.com/onelogin/php-saml/blob/master/demo1/index.php#L41)

```
$nameId = $session->get('saml_nameid');
$sessionIndex = $session->get('saml_sessionindex');
$saml_auth->logout(null, array(), $nameId, $sessionIndex);
```

Can you try that and if works for you, provide a PR?

**Comment by wintercomic** [comment]
I add

```
// SSO SAML Login flag
$session->set('saml_login', 1);

$nameId = $saml_auth->getNameId();
$session->set('saml_nameid', $nameId);

$sessionIndex = $saml_auth->getSessionIndex();
$session->set('saml_sessionindex', $sessionIndex);
```

and 

```
$nameId = $session->get('saml_nameid');
$sessionIndex = $session->get('saml_sessionindex');
$saml_auth->logout(null, array(), $nameId, $sessionIndex);
```

in all login and logout. Now  Joomla can pass the correct NameId format to ADFS.

```
<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                     ID="ONELOGIN_5124f0ce16427def3512659d44808d9b81f28567"
                     Version="2.0"
                     IssueInstant="2016-08-29T02:36:10Z"
                     Destination="ADFS"
                     >
    <saml:Issuer>Joomla</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">RcTZaC9QcYRA15HBOgRQQPyPdmb87u9/HAov92B8xuQ=</saml:NameID>
    <samlp:SessionIndex>_50e8d4ef-de6c-4462-9baf-ed185d12ad1b</samlp:SessionIndex>
</samlp:LogoutRequest>

```

**Comment by wintercomic** [comment]
If I login as a new user at first time, I will get "USER NOT EXISTS AND FAILED THE CREATION PROCESS" Error message and user is not logged in . I go to back-end and  look at user list,  I find the user already successfully create. I click login again and user can login without any problem.

**Comment by pitbulk** [comment]
What Joomla version are you using?

Can you add a debuger at:
https://github.com/onelogin/joomla-saml/blob/master/plg_user_oneloginsaml/oneloginsaml.php#L147
and see the value of the $return value after execute

```
 $return = $model->register($data);
```

And also the value of the $errors after

```
$errors = $model->getErrors();
```

**Comment by pitbulk** [comment]
On the register method of Joomla 3.6:
https://github.com/joomla/joomla-cms/blob/3.6.0/components/com_users/models/registration.php#L381

I see that false is also sent by this method if the sending mail process fails.
Maybe I should not use register because I dont think we need in the SAML plugin this mail stuff.
also the getErrors method is marked as deprecated and we shouldnt use it.

Meanwhile and in order to fix your issue, can you  in case of $return == false, check if the user was really created or not by calling

```
 $result = get_user_from_joomla($matcher, $username, $email);
```

And only when this fails execute the t "USER NOT EXISTS AND FAILED THE CREATION PROCESS" block?

(and detect if that was the case to not execute the  get_user_from_joomla method again
later (after the if statement).

**Comment by wintercomic** [comment]
I am not familiar with php, I place the the checking after get_user_from_joomla method: 

```
$return = $model->register($data);

$result = get_user_from_joomla($matcher, $username, $email);

if ($return === false && $result == null) {
     $errors = $model->getErrors();
     $response->status = JAuthentication::STATUS_FAILURE;
     $response->message = 'USER NOT EXISTS AND FAILED THE CREATION PROCESS';
     $app->redirect($login_url, $response->message, 'error');
 }
```

it seems work.

**Comment by pitbulk** [comment]
Yes, that also works.

I plan to release a new version of php-saml next week so I will then release a new joomla-saml version with the update library and those improvements.

What Joomla version you used?

**Comment by wintercomic** [comment]
I just update to the latest Joomla version, 3.6.2 .

**Comment by Michandrz** [comment]
Since this is from 2016, I assume the issue has been fixed?

**Comment by Michandrz** [comment]
@pitbulk

**Comment by pitbulk** [comment]
In 2-3 weeks, I will spend some time updating this extension and making it compatible with latest release as well.
