### ISSUE TITLE
Unable to work with Azure

### ISSUE THREAD

**Issue by provosta99** [onelogin/joomla-saml#11]
Trying to configure the plugin with Azure with no success all parameter are in place but we have always this error
AADSTS700016: Application with identifier 'https://sts.windows.net/12cb4e1a-42da-491c-90e1-7a7a9753506f/' was not found in the directory '12cb4e1a-42da-491c-90e1-7a7a9753506f'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
What's wrong?

**Comment by Michandrz** [comment]
Did you create the application in azure? After doing that there are several parameters that need to line up in order to make it worK.  The one I overlooked was setting the SP identity.

**Comment by provosta99** [comment]
Found a guide for setting up the onelogin for Wordpress and it gave me the details of the configuration that i was looking for.
https://cloudrun.co.uk/azure-ad/configure-wordpress-sso-with-azure-ad/

**Comment by Michandrz** [comment]
Cool, so I assume you figured out it was just a parameter, @pitbulk please close.
