### ISSUE TITLE
NO_AUTHENTICATED invalid_response WHEN integrated with Joomla 3.6.5

### ISSUE THREAD

**Issue by baoqphan** [onelogin/joomla-saml#2]
Hi,
I am new to onelogin. I want to integrate my Joomla Site with OneLogin. I installed onelogin joomla plugin (for 3.3) and oneplugin library. I set up all the settings. I got 

NO_AUTHENTICATED
invalid_response

When tried to login with a valid user and password. 

Please help

**Comment by pitbulk** [comment]
Enable the "debug" mode on the SAML settings, and also on Joomla/PHP, the reason for the invalid_response should be printed and then you will be able to fix the settings on IdP or SP in order to solve the issue.

**Comment by baoqphan** [comment]
Hi,

1. I enabled the Debug Mode on the Advanced Setting of the OneLogin
authenticaiton plugin
2. I enabled the joomla Global configuration -> System -> Debug System.


I can't see the reason for "invalid_response".

Thank you very much.

Sincerely,

Bao Q Phan

"Easy to take off. Harder to Fly"

**Comment by pitbulk** [comment]
Hi,

Edit oneloginsaml.php, [line 65](https://github.com/onelogin/joomla-saml/blob/master/plg_user_oneloginsaml/oneloginsaml.php#L65)
```
$errors = $saml_auth->getErrors();
if (!empty($errors) && $debug) {
            $msg_error .= '<br>'.implode(', ', $errors);
}
$msg_error .= '<br>'.$saml_auth->getLastErrorReason();
```

**Comment by baoqphan** [comment]
Here is more details on the error: 

Error
NO_AUTHENTICATED
invalid_response
The response has an empty Destination value

**Comment by baoqphan** [comment]
Here is the response (decoded):

<samlp:Response xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="R24c4b5a7a57032afb128ac49314fcea4511325d9" Version="2.0" IssueInstant="2017-04-10T23:25:10Z" Destination="" InResponseTo="ONELOGIN_2f68360e911a959de7f518056f4e091dba9a0256"><saml:Issuer>https://app.onelogin.com/saml/metadata/645821</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2.0" ID="pfxf4c8a223-4781-eac5-864f-1d92a2819393" IssueInstant="2017-04-10T23:25:10Z"><saml:Issuer>https://app.onelogin.com/saml/metadata/645821</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#pfxf4c8a223-4781-eac5-864f-1d92a2819393"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>f1fpqPXwWaJt9PqxeecI03kSUg0=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>zsQy30P6LPMNiKMxvcCYCMgCLq7yMZdVuSeJjUy/BLFV/fyq20miUs5l1dZPX/OcZsrHDJDmDOk6KZ7RDnCeHBNakwF5c4g25t6LdKwJdMo0Nw+Lt5ePKGJVYsZeWUaMOgT0dBFsI5vRdvfkc/AD56ILR+lSH3s98KBnMM1sWaW9HmhhmInQpFV06ZWt1BFp6P6+7B88s70yPSVqjSfg1Pg5J683BTqgMOzAqsVc1TNn8umH09XLAysDP3CkloHXJfRYls7MNpNJspq+VZID9mFx44rpkwhlCi15m+WL6f1TVDWzJwGci428p/MHb8YCrBBuIVWEM7ILRRUUVYYHGg==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIELzCCAxegAwIBAgIUAdv4S2pFg9crJzHD2SqETdiA4VMwDQYJKoZIhvcNAQEFBQAwYDELMAkGA1UEBhMCVVMxGDAWBgNVBAoMD1RFQVBJT0NBIExPVU5HRTEVMBMGA1UECwwMT25lTG9naW4gSWRQMSAwHgYDVQQDDBdPbmVMb2dpbiBBY2NvdW50IDEwNDEyMjAeFw0xNzA0MDUwNDMwMDdaFw0yMjA0MDYwNDMwMDdaMGAxCzAJBgNVBAYTAlVTMRgwFgYDVQQKDA9URUFQSU9DQSBMT1VOR0UxFTATBgNVBAsMDE9uZUxvZ2luIElkUDEgMB4GA1UEAwwXT25lTG9naW4gQWNjb3VudCAxMDQxMjIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDhg8pozVj23Ajy8LbZnGAcq2nVpL49zEW0eVPPXwoXyGm18VyBDUR+TiTcjlg+/4m7qCAIS/OvZCQXp2kQeAtKOfa34WGF9RdlARqDawuhvBsmLRj10bfu8tHac+ZBNtoCmMNz+kZ5/JUd6UBlcBmP9CRfOm1KNHGHoK/h8bcTnjs9beoPGPNNxySQmzDX8ogCMMX4IsWM4cr/2KxipvPWxHC2TuQmsm+tpaO4bM1r3X1IkLw+QCKt8Rm3Safzq+a2UUtcDli0Q0T4/+0bQEsHyi67N66zGN8ldAYIX8bQ/2YM8OKkgB+4ChGDwvvxPROFMpQqo5outaxjD1pF7o1BAgMBAAGjgeAwgd0wDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU6nW7KdawquM8Xa4bNNUCi1yhKmgwgZ0GA1UdIwSBlTCBkoAU6nW7KdawquM8Xa4bNNUCi1yhKmihZKRiMGAxCzAJBgNVBAYTAlVTMRgwFgYDVQQKDA9URUFQSU9DQSBMT1VOR0UxFTATBgNVBAsMDE9uZUxvZ2luIElkUDEgMB4GA1UEAwwXT25lTG9naW4gQWNjb3VudCAxMDQxMjKCFAHb+EtqRYPXKycxw9kqhE3YgOFTMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQUFAAOCAQEAy/c90o2lhzT68nKze5rWJ5+omPTzYv3eEQ81+DtIhmIyE7u0u+EUooDFNinOdBKV1vab/7igBnxjUm+pk6qzRm+c8Up8k1eI4ZI/EPsq34C3ZOsw6w/ZsgbDuLkODC6lf7qQku75xiTXEarQBA41T0hWvSCfVxLUzMYUw+qk8iGU/HV02ft7BR4+6MKXKf9DOoejD2HICVnEFTVTyBDtouO3THRJ0taKkUtQ5imKdy4ElMUlwZVdjCqLovH+TCMiqlxgtIlKpOJ/crQqy4lUvG5F4L/EN8xdphiw0UBtImjmuSz+vwH4OCS04pdGZCXKECZJgQd2pM6lJ3K1Cj/3oA==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml:Subject><saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">baoquocphan@gmail.com</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData NotOnOrAfter="2017-04-10T23:28:10Z" Recipient="" InResponseTo="ONELOGIN_2f68360e911a959de7f518056f4e091dba9a0256"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="2017-04-10T23:22:10Z" NotOnOrAfter="2017-04-10T23:28:10Z"><saml:AudienceRestriction><saml:Audience/></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="2017-04-10T23:25:09Z" SessionNotOnOrAfter="2017-04-11T23:25:10Z" SessionIndex="_6ac9b960-0072-0135-f3d2-0a6071e3b803"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement><saml:AttributeStatement><saml:Attribute Name="E-Mail" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"/></saml:Attribute><saml:Attribute Name="PersonImmutableID" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"/></saml:Attribute><saml:Attribute Name="Username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"/></saml:Attribute><saml:Attribute Name="LastName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"/></saml:Attribute><saml:Attribute Name="FirstName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"/></saml:Attribute><saml:Attribute Name="Group" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"/></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>

**Comment by baoqphan** [comment]
So, The Destination field from the SAML response is actual empty

Destination=""

**Comment by pitbulk** [comment]
You need to provided on the [Onelogin Test Connector](https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector) a valid Recipient (in this case same than ACS URL).

**Comment by baoqphan** [comment]
Hi, I am using Joomla App in OneLogin and it goes against the joomla site. 

Do I need to configure the Onelogin Test Connector?

**Comment by pitbulk** [comment]
Yes since it seems Joomla App in OneLogin works with previous versions of joomla-saml but not with the latest version that requires a Destination value.

**Comment by Michandrz** [comment]
@pitbulk 3 years old now. Please close.
