### ISSUE TITLE
Bug in joomla-saml/onelogin/settings.php

### ISSUE THREAD

**Issue by thomaslanger** [onelogin/joomla-saml#4]
On line 9+10
$saml_settings = array (
    'strict' => $saml_params->get('onelogin_saml_advanced_settings_debug'),
    'debug' => $saml_params->get('onelogin_saml_advanced_settings_strict_mode'),

Fix:

    'strict' => $saml_params->get('onelogin_saml_advanced_settings_strict_mode'),
    'debug' => $saml_params->get('onelogin_saml_advanced_settings_debug'),

**Comment by pitbulk** [comment]
Thanks for contribute.
