### ISSUE TITLE
Getting NO_USERNAME in authorization process

### ISSUE THREAD

**Issue by ilmoralito** [onelogin/joomla-saml#5]
Hello, I try to integrate OneLogin with Joomla, after installing the plugins, I have created a Joomla 3.x application in OneLogin, with the information in the SSO tab I have filled the plugin fields in the identity poviders settings tab, finally in OneLogin in the Configuration tab I have added the Consumer URL and Single Logout URL values according to the examples provided by changing only the location of my Joomla portal. Finally I have added a link to the login form in Joomla.

By clicking on the link, I get redirected to OneLogin where I provide the credentials with which I created the account in OneLogin, this same user I created it in Joomla, by providing the username and password I get redirected to Joomla but the message no_username is always generated

Debugging the file `/plugins/user/oneloginsaml/oneloginsaml.php I find that the error occurs in this condition

```
        $matcher = $plgParams->get('onelogin_saml_account_matcher', 'username');

        if (empty($username) && $matcher == 'username') {
            $response->status = JAuthentication::STATUS_FAILURE;
            $response->message = 'NO_USERNAME';
            $app->redirect($login_url, $response->message, 'error');
        }
```
Could you give me an idea of the reason why username is always empty, thanks in advance

In the plugin Options tabs I changed Match Joomla account by to E-Mail and when I try I get the message NO_MAIL

**Comment by pitbulk** [comment]
Review what attributes are included in AttributeStatement of the SAMLResponse generated by the IdP as well as the values you set on the Attribute Mapping section of the Joomla SAML Settings.

**Comment by Michandrz** [comment]
@pitbulk Close please, no response in months.
